/** Local Figma exports for Số dư (nodes 41:3035, 41:3226, 41:3428). */
export const WALLET_ASSETS = {
  walletCards: '/figma/wallet/icon-wallet-cards.svg',
  shield: '/figma/wallet/icon-shield-check.svg',
  plus: '/figma/wallet/icon-plus-circle.svg',
  plusMuted: '/figma/wallet/icon-plus-muted.svg',
  arrowDown: '/figma/wallet/icon-arrow-down.svg',
  arrowActive: '/figma/wallet/icon-arrow-active.svg',
  list: '/figma/wallet/icon-list.svg',
  listActive: '/figma/wallet/icon-list-active.svg',
  banknote: '/figma/wallet/icon-banknote.svg',
  phone: '/figma/wallet/icon-smartphone.svg',
  qr: '/figma/wallet/icon-qr.svg',
  webhook: '/figma/wallet/icon-webhook.svg',
  arrowUpRight: '/figma/wallet/icon-arrow-up-right.svg',
  check: '/figma/wallet/icon-circle-check.svg',
  receipt: '/figma/wallet/icon-receipt.svg',
  landmark: '/figma/wallet/icon-landmark.svg',
  card: '/figma/wallet/icon-card.svg',
  userCheck: '/figma/wallet/icon-user-check.svg',
  dollar: '/figma/wallet/icon-dollar.svg',
  clock: '/figma/wallet/icon-clock.svg',
  send: '/figma/wallet/icon-send.svg',
  lock: '/figma/wallet/icon-lock.svg',
  swap: '/figma/wallet/icon-swap.svg',
  chevron: '/figma/wallet/icon-chevron.svg',
  calendar: '/figma/wallet/icon-calendar.svg',
  checkBig: '/figma/wallet/icon-check-big.svg',
  refund: '/figma/wallet/icon-refund.svg',
  bag: '/figma/wallet/icon-bag.svg',
  badge: '/figma/wallet/icon-badge.svg',
  info: '/figma/wallet/icon-info.svg',
} as const
