import { lazy } from 'react'

// Reuse the same lazy identity in standalone routes, map panels and workspaces.
export const HomePage = lazy(() => import('./HomePage').then(module => ({ default: module.HomePage })))
export const ExplorePage = lazy(() => import('./ExplorePage').then(module => ({ default: module.ExplorePage })))
export const LoginPage = lazy(() => import('./LoginPage').then(module => ({ default: module.LoginPage })))
export const RegisterPage = lazy(() => import('./RegisterPage').then(module => ({ default: module.RegisterPage })))
export const ForgotPasswordPage = lazy(() => import('./ForgotPasswordPage').then(module => ({ default: module.ForgotPasswordPage })))
export const ResetPasswordPage = lazy(() => import('./ResetPasswordPage').then(module => ({ default: module.ResetPasswordPage })))
export const AuthCallbackPage = lazy(() => import('./ResetPasswordPage').then(module => ({ default: module.AuthCallbackPage })))
export const PrivacyPolicyPage = lazy(() => import('./LegalPage').then(module => ({ default: module.PrivacyPolicyPage })))
export const TermsOfServicePage = lazy(() => import('./LegalPage').then(module => ({ default: module.TermsOfServicePage })))
export const CreateRentalPostPage = lazy(() => import('./CreateRentalPostPage').then(module => ({ default: module.CreateRentalPostPage })))
export const EditRentalPostPage = lazy(() => import('./EditRentalPostPage').then(module => ({ default: module.EditRentalPostPage })))
export const PaymentWaitingPage = lazy(() => import('./PaymentWaitingPage').then(module => ({ default: module.PaymentWaitingPage })))
export const AdminModerationPage = lazy(() => import('./AdminModerationPage').then(module => ({ default: module.AdminModerationPage })))
export const SavedPostsPage = lazy(() => import('./SavedPostsPage').then(module => ({ default: module.SavedPostsPage })))
export const NotificationsPage = lazy(() => import('./NotificationsPage').then(module => ({ default: module.NotificationsPage })))
export const PaymentPage = lazy(() => import('./PaymentPage').then(module => ({ default: module.PaymentPage })))
export const ProfilePage = lazy(() => import('./ProfilePage').then(module => ({ default: module.ProfilePage })))
export const MarketplacePage = lazy(() => import('./MarketplacePage').then(module => ({ default: module.MarketplacePage })))
export const WantedPostsPage = lazy(() => import('./WantedPostsPage').then(module => ({ default: module.WantedPostsPage })))
export const ActivitiesPage = lazy(() => import('./ActivitiesPage').then(module => ({ default: module.ActivitiesPage })))
export const MyPostsPage = lazy(() => import('./MyPostsPage').then(module => ({ default: module.MyPostsPage })))
export const RoommateWorkspace = lazy(() => import('../components/roommates/RoommateWorkspace').then(module => ({ default: module.RoommateWorkspace })))
export const MapAppointmentsPanel = lazy(() => import('../components/map/MapAppointmentsPanel').then(module => ({ default: module.MapAppointmentsPanel })))
export const MapMessagesPanel = lazy(() => import('../components/map/MapMessagesPanel').then(module => ({ default: module.MapMessagesPanel })))
